version: '2'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elk-stack-elasticsearch
    image: elk-stack-elasticsearch:6.2.3
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /home/despegar/data/elastic-data:/usr/share/elasticsearch/data
    environment: []
      #- ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    #restart: always
    networks: ["elk"]
  logstash:
    build: ./logstash
    image: elk-stack-logstash:6.2.3
    container_name: elk-stack-logstash
    ports: 
      - "5000:5000"
      - "4560:4560"
    networks: ["elk"]
    #restart: always
    depends_on: ["elasticsearch"]
  kibana:
    build: ./kibana
    image: elk-stack-kibana:6.2.3
    container_name: elk-stack-kibana
    ports: 
      - "9290:5601"
    networks: ["elk"]
    #restart: always
    depends_on: ["elasticsearch"]
  metricbeat:
    build: ./metricbeat
    image: elk-stack-metrobeat:6.2.3
    container_name: elk-stack-metricbeat
    networks: ["elk"]
    #restart: always
    depends_on: ["elasticsearch", "kibana"]
networks: 
  elk:
