actions:
  1:
    action: delete_indices
    description: >-
      Delete older indices.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
      - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: ${DAYS:7}
